module.exports = {
  prompt: {
    useEmoji: false,
    messages: {
      type: 'Select the type of change that you\'re committing:',
      scope: 'Denote the scope of this change (optional):',
      subject: 'Write a short, imperative summary:\n',
      body: 'Provide a longer description (optional). Use "|" for new line:\n',
      breaking: 'List breaking changes (optional):\n',
      footerPrefixesSelect: 'Select footer prefix (optional):',
      customFooterPrefix: 'Input custom footer prefix:\n',
      footer: 'List any issues closed by this change (optional). E.g.: #31, #34:\n',
      confirmCommit: 'Are you sure you want to proceed with the commit above?',
    },
    types: [
      { value: 'feat', name: 'feat:     A new feature' },
      { value: 'fix', name: 'fix:      A bug fix' },
      { value: 'docs', name: 'docs:     Documentation only changes' },
      { value: 'style', name: 'style:    Changes that do not affect the meaning of the code' },
      { value: 'refactor', name: 'refactor: A code change that neither fixes a bug nor adds a feature' },
      { value: 'perf', name: 'perf:     A code change that improves performance' },
      { value: 'test', name: 'test:     Adding missing tests or correcting existing tests' },
      { value: 'build', name: 'build:    Changes that affect the build system or external dependencies' },
      { value: 'ci', name: 'ci:       Changes to CI configuration files and scripts' },
      { value: 'chore', name: 'chore:    Other changes that do not modify src or test files' },
      { value: 'revert', name: 'revert:   Revert a previous commit' },
    ],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    scopeOverrides: {},
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    issuePrefixes: [{ value: '#', name: '#: issue id' }],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
  },
};
